plugins:
  - jekyll-paginate

title: ğŸç«¹ç¬‹ğŸ
description: ï¼ˆåŒæ‰‹åˆåï¼‰

paginate: 10
paginate_path: /page/:num/
permalink: /:title/

url: "https://katzeimmondlicht.github.io" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap